# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/a1aeefa1-5693-4548-91c8-d12415f4ee36";
    fsType = "ext4";
  };

  fileSystems."/Media" = {
    device = "/dev/disk/by-uuid/aedea097-9f0a-4a80-8b6b-dc4ce833a616";
    fsType = "ext4";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/27b33ca0-6597-427c-a751-d8b88c3dd7d3"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
